### ISSUE TITLE
Invalid Keycloak response

### ISSUE THREAD

**Issue by emi662002** [kozmoz/thuisbezorgd-scraper#11]
I'm getting 401 "Invalid Keycloak response", is the api not working anymore ? I think it is because of 2FA

**Comment by kozmoz** [comment]
Yes, receiving the list of orders should definitely work. I use it on a daily basis.
Do the same credentials also work for the portal website? https://restaurant.thuisbezorgd.nl/

**Comment by emi662002** [comment]
No wonder I'm not using partner credentials. Sorry for the noise. Thanks!
