### ISSUE TITLE
Legality of scarping thuisbezorgd

### ISSUE THREAD

**Issue by Mat-thieu** [kozmoz/thuisbezorgd-scraper#2]
Hi,

I'm planning to scrape thuisbezorgd, not even more than 1 request an hour, but I'm not sure if it's actually allowed, I can't find a conclusive answer.

What's your stance on this issue?

**Comment by kozmoz** [comment]
I cannot give you the formal legal answer. 

For personal use I don't think it's illegal. I use it to aggregate the results from multiple websites and present them within one single screen. The screen is updated once a minute.

On the other hand I think it's not allowed to use this scraper within a commercial product. Then you have to go the T-Connect route or use an API of them I'm not aware of.

**Comment by Mat-thieu** [comment]
@kozmoz Thanks! I'll follow your advice in that case.
