### ISSUE TITLE
Status change functionality

### ISSUE THREAD

**Issue by moparlakci** [kozmoz/thuisbezorgd-scraper#5]
Hello 

Great scraper!

Do you also have an implementation to change order status?
eg. Confirmed, Kitchen, Delivery...

Have a nice day!

**Comment by kozmoz** [comment]
Not using the service of Thuisbezorgd.nl / Takeaway.com anymore so unfortunately not able to add new functionality.

**Comment by moparlakci** [comment]
Okay actually found out today that there is an official REST API. Going to use that instead ;)

**Comment by RWOverdijk** [comment]
@moparlakci Where can I find info on this API? I'd be very grateful if you could share that!

**Comment by moparlakci** [comment]
@RWOverdijk

Contact: posapi@takeaway.com

**Comment by RWOverdijk** [comment]
@moparlakci Thanks! :) Do you have good experiences with this integration?

**Comment by moparlakci** [comment]
@RWOverdijk Yes of course, they let you test on the production site. Try to use 8888 as postal code on the website to see any running api integrations of other people using the posapi ;)

**Comment by kozmoz** [comment]
Reconnecting with takeaway.com service. Might update this project soon. But prefer to connect to the official API. 
Thanks for the contact email @moparlakci, let's see if they respond to my question about POS API access.

**Comment by kozmoz** [comment]
Implemented in version 2.3.2
