### ISSUE TITLE
naam velden leeg

### ISSUE THREAD

**Issue by R0B3RDV** [kozmoz/thuisbezorgd-scraper#6]
Hoi, 

Ervaar jij hetzelfde op dit moment, dat de velden: name leeg zijn?

grt Robert

**Comment by kozmoz** [comment]
Hallo Robert,

Geen idee, ik maak geen gebruik meer van Thuisbezorgd, dus kan dit helaas niet controleren.

Gr,
Rob

**Comment by kozmoz** [comment]
No longer applicable to version 2.
